clock: Build views by code instead of inflating from xml
When we try to inflate views from xml, it throws classloader issues.
so let's build views by code.

Fixes:
java.lang.ClassCastException: com.libremobileos.clock.AnimatableClockView cannot be cast to com.libremobileos.clock.AnimatableClockView